// buuIdMapping.js
import { fs2, path, idk } from './importer.js';
import conf from './config.js';
import { c } from './color.js';
const buuUserPath = conf.sessionUserBidPath || './buuUsers';
const freshMappedUser = `${buuUserPath}/${conf.freshMappedUser}`;
const dsgvoAcceptOnlyUser = `${buuUserPath}/${conf.dsgvoAcceptOnlyUser}`;
const dsgvoRejectOnlyUser = `${buuUserPath}/${conf.dsgvoRejectOnlyUser}`;
const verifyOnlyUser = `${buuUserPath}/${conf.verifyOnlyUser}`;
const rejectOnlyUser = `${buuUserPath}/${conf.rejectOnlyUser}`;
const dsgvoAndVerifyUser = `${buuUserPath}/${conf.dsgvoAndVerifyUser}`;
const sessionPath = conf.sessionPath || './buuSession';
const jsonD = '.json';
const lidM = 'lid-mapping-';
const lidMrev = '_reverse';
const utf8 = 'utf-8';
export const clean = (id) => { if (!id) return null; 
return id.split('@')[0].split(':')[0]; 
};
export const buildBid = (jid, lid) => `${clean(jid)}jid${clean(lid)}lid`;
const createUserTemplate = (jid, lid, bid) => ({ identity: { bid: `${jid}jid${lid}lid`, phone: `+${jid}`, jid: `${jid}@s.whatsapp.net`, lid: `${lid}@lid`, cleanJid: jid, cleanLid: lid }, status: { dsgvo: { accepted: false, rejected: false, acceptedAt: null }, verified: false, unverify: true, mappedAt: new Date().toISOString(), registeredAt: null }, progression: { level: 0, prestige: 0, xp: 0, neededXpForLvOrPrestigeUp: 743 }, casino: { gamesPlayed: 0, lastWin: 0, totalWin: 0, highestWin: 0, winStreak: 0, highestWinStreak: 0, lastLoss: 0, totalLoss: 0, highestLoss: 0, lossStreak: 0, highestLossStreak: 0 }, wallet: { copper: 0, silver: 0, gold: 0, platin: 0 }, bank: { active: false, copper: 0, silver: 0, gold: 0, platin: 0 }, rewards: { lastDaily: null, lastWeekly: null, lastMonthly: null, lastYearly: null } });
async function findProfilePath(bid) { const checkPaths = [ path.join(buuUserPath, `${bid}${jsonD}`), path.join(freshMappedUser, `${bid}${jsonD}`), path.join(dsgvoAndVerifyUser, `${bid}${jsonD}`), path.join(dsgvoAcceptOnlyUser, `${bid}${jsonD}`), path.join(dsgvoRejectOnlyUser, `${bid}${jsonD}`), path.join(verifyOnlyUser, `${bid}${jsonD}`), path.join(rejectOnlyUser, `${bid}${jsonD}`) ]; for (const p of checkPaths) { const exists = await fs2.stat(p).catch(() => false);
if (exists) return p;
} return null;
} export async function saveProfile(p) { if (!p?.identity?.bid) return false;
try { const existingPath = await findProfilePath(p.identity.bid);
const finalPath = existingPath || path.join(buuUserPath, `${p.identity.bid}${jsonD}`);
await fs2.mkdir(path.dirname(finalPath), { recursive: true });
await fs2.writeFile(finalPath, JSON.stringify(p, null, 2));
return true;
} catch (e) { console.error(`${c.red}[FS ERROR]\nFehler beim Speichern:${c.reset}`, e);
return false;
} } export async function checkAndCreateImmediateProfile(resultMapping) { if (resultMapping && resultMapping.jid !== idk && resultMapping.lid !== idk) { const jid = clean(resultMapping.jid);
const lid = clean(resultMapping.lid);
const bid = buildBid(jid, lid);
const profileExists = await findProfilePath(bid);
if (!profileExists) { await saveProfile(createUserTemplate(jid, lid, bid));
console.log(`${c.green}[MAPPING]\nSofort-Profil erstellt für:${c.reset} ${jid}`);
} } } export async function processMappingFile(file) { if (!file.startsWith(lidM) || !file.endsWith(jsonD)) return;
try { await new Promise(r => setTimeout(r, 347));
const rawData = await fs2.readFile(path.join(sessionPath, file), utf8);
if (!rawData.trim()) return;
const raw = JSON.parse(rawData);
const rawCleaned = clean(raw);
const isRev = file.includes(lidMrev);
let jid, lid;
if (isRev) { // LID TO JID
jid = rawCleaned;
lid = clean(file.replace(lidM, '').replace(`${lidMrev}${jsonD}`, ''));
} else { // JID TO LID
lid = rawCleaned;
jid = clean(file.replace(lidM, '').replace(jsonD, ''));
} if (jid && lid && jid !== lid) { const bid = buildBid(jid, lid);
const profileExists = await findProfilePath(bid);
if (!profileExists) { await saveProfile(createUserTemplate(jid, lid, bid));
console.log(`${c.bgCyan}${c.black}[MAPPING]${c.reset} ${c.cyan}Neuer User verknüpft:${c.reset}\n${c.bgBlue}${c.black}JID:${c.reset} ${c.blue} ${jid}${c.reset}\n${c.bgRed}${c.black}LID:${c.reset} ${c.red}${lid}${c.reset}\n${c.bgBrightMagenta}${c.black}BID:${c.reset} ${c.brightMagenta}${bid}${c.reset}\n`);
} } } catch (e) { console.error(`${c.bgRed}${c.black}[MAPPING ERROR]${c.reset}\n${c.red}Fehler bei Datei ${file}:${c.reset}`, e);
} } export async function syncAllBuuUsers() { try { const files = await fs2.readdir(sessionPath).catch(() => []);
for (const file of files) { await processMappingFile(file);
} } catch (err) { console.error(`${c.bgRed}${c.black}[MAPPING ERROR]${c.reset}\n${c.red}Fehler beim Einlesen des Ordners:${c.reset}`, err);
} }