// connect.js
import conf from './config.js';
import { c } from './color.js';
import { handler } from './handler.js';
import { fs, readline, qrcode, cs, pino, idk, whiskeysocketsBaileys, makeWASocket, buuBotAuthState, fetchLatestBaileysVersion, makeCacheableSignalKeyStore, store, DisconnectReason, generateWAMessageFromContent, proto } from './importer.js';
import { syncAllBuuUsers, clean, migrateOldBuuUsers } from './buuIdMapping.js';
if (typeof buuBotAuthState !== 'function') { console.error(`${c.bgRed}${c.black}${c.bold}Fehler:${c.reset} ${c.red}${c.bold}useMultiFileAuthState konnte nicht gefunden werden!${c.reset}`);
process.exit(1);
} const cs2 = `${cs}${cs}`;
const sessionPath = conf.sessionPath;
const logger = pino({ level: conf.loggerLevel });
let mappingInterval = null;
let currentSock = null;
let abortController = null;
function question(text) { const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
return rl.question(text).finally(() => rl.close());
} function setupAbortListener() { if (abortController) abortController.abort();
abortController = new AbortController();
const { signal } = abortController;
process.stdin.setRawMode(true);
process.stdin.resume();
process.stdin.setEncoding('utf8');
const keyHandler = (key) => { if (signal.aborted) { process.stdin.off('data', keyHandler);
return;
} const cleanKey = key.toLowerCase().trim();
if (cleanKey === 'x') { console.log(`\n${c.yellow}→ Programm wird beendet.${c.reset}`);
process.exit(0);
} if (cleanKey === 'b') { process.stdin.off('data', keyHandler);
process.stdin.setRawMode(false);
abortController.abort();
if (currentSock) { currentSock.ev.removeAllListeners('connection.update');
currentSock.ws.close();
} console.clear();
startWhatsAppBotMadeByHonneybuuModz();
} };
process.stdin.on('data', keyHandler);
} function disableAbortListener() { if (abortController) abortController.abort();
try { process.stdin.setRawMode(false);
} catch(e){} } function formatSmartPairingCodeColor(code) { if (!code) return '';
return code.split('').map(char => { if (/[A-Z]/i.test(char)) return `${c.brightMagenta}${c.bold}${char}${c.reset}`;
if (/[0-9]/.test(char)) return `${c.brightGreen}${c.bold}${char}${c.reset}`;
return char;
}).join('');
} function getPairingCodeOutput(buuClientColoredPairingCode) { return "\n" + `${c.bgCyan}${c.black}${c.bold}${cs2}${c.reset}\n${c.bold}${c.green}DEIN PAIRING CODE:${c.reset}\n` + buuClientColoredPairingCode + `\n\n${c.bgCyan}${c.black}Gib diesen Code jetzt in deinem WhatsApp unter${c.reset}\n${c.cyan} 1. → Verknüpfte Geräte\n2. → Gerät verknüpfen\n3. → Mit Telefonnummer ein.${c.reset}\n\n${c.magenta}[b] Back to Menu|[x] Exit Script${c.reset}\n${c.bgCyan}${c.black}${c.bold}${cs2}${c.reset}`;
} export async function startWhatsAppBotMadeByHonneybuuModz() { disableAbortListener();
let sessionInfo = null;
let brokenSessionMenu = `${c.yellow}⚠ Session-Datei gefunden, aber nicht lesbar.${c.reset}\n${c.bgMagenta}${c.black}${c.bold}${cs2}${c.reset}\n${c.bold}${c.cyan}${conf.name.toUpperCase()} SETUP${c.reset}\n${c.magenta}BY:${c.reset} ${c.bgMagenta}${c.black}${c.bold}${conf.buuTeam}${c.reset}\n${c.magenta}version:${c.reset} ${c.bgMagenta}${c.black}${c.bold}${conf.version}${c.reset}\n${c.bgMagenta}${c.black}${c.bold}${cs2}${c.reset}`;
let workingSessionMenu = '';
let noSession = `${c.bgYellow}${c.black}${c.bold} ⚠ KEINE SESSION GEFUNDEN ${c.reset}\n${c.bgCyan}${c.black}${c.bold} [q] ${c.reset} ${c.cyan}QR Pairing${c.reset}\n${c.bgMagenta}${c.black}${c.bold} [p] ${c.reset} ${c.magenta}Pairing Code${c.reset}\n${c.bgYellow}${c.black}${c.bold}[x] ${c.reset}${c.yellow}Script beenden${c.reset}`;
try { if (fs.existsSync(sessionPath)) { const { state } = await buuBotAuthState(sessionPath);
if (state.creds && state.creds.me) { const name = state.creds.me.name || idk || '';
const rawId = state.creds.me.id || idk || '';
const hostPhone = clean(rawId) || idk || '';
const hostJid = hostPhone !== idk ? `${hostPhone}` : idk;
const rawLid = state.creds.me.lid || '';
const hostLinkedId = clean(rawLid) || idk;
const hostLid = hostLinkedId !== idk ? `${hostLinkedId}` : idk;
const hostBid = (hostJid !== idk && hostLid !== idk) ? `${hostJid}jid${hostLid}lid` : idk;
const sidByJid = state.creds.me.id?.split(':')[1]?.split('@')[0];
const sidByLid = state.creds.me.lid?.split(':')[1]?.split('@')[0];
const hostSid = (sidByJid && sidByJid === sidByLid) ? sidByJid : (sidByJid || idk);
sessionInfo = { name, hostJid, hostLid, hostBid, hostPhone, hostSid };
const hostSessionData = `${c.bgCyan}${c.black}${c.bold}${cs2}${c.reset}\n${c.green}👤 Name: ${c.magenta}${c.bold}${sessionInfo.name}${c.reset}\n${c.green}📱 Nummer: ${c.magenta}+${sessionInfo.hostPhone}${c.reset}\n${c.green}JID: ${c.magenta}${sessionInfo.hostJid}@s.whatsapp.net${c.reset}\n${c.green}LID: ${c.magenta}${sessionInfo.hostLid}@lid${c.reset}\n${c.green}BID: ${c.magenta}${sessionInfo.hostBid}${c.reset}\n${c.green}SESSION ID: (SID) ${c.magenta}${sessionInfo.hostSid}${c.reset}\n${c.bgCyan}${c.black}${c.bold}${cs2}${c.reset}`;
workingSessionMenu = `${c.bgGreen}${c.black}${c.bold} ✓ BESTEHENDE SESSION GEFUNDEN ${c.reset}\n${hostSessionData}\n${c.bgGreen}${c.black}${c.bold} [y] ${c.reset}\n${c.green}Alte Session starten${c.reset}\n${c.bgRed}${c.black}${c.bold} [n] ${c.reset}\n${c.red}Neue Session starten (Alte löschen)${c.reset}\n${c.bgYellow}${c.black}${c.bold} [x] ${c.reset} ${c.yellow}Script beenden${c.reset}`;
} } } catch (err) { console.log(`${brokenSessionMenu}\n`);
} let choice = '';
if (sessionInfo) { console.log(`${workingSessionMenu}\n`);
choice = await question(`${c.bgMagenta}${c.black}${c.bold}Deine Wahl: ${c.reset}`);
choice = choice.toLowerCase().trim();
if (choice === 'x') { process.exit(0);
} if (choice === 'n') { if (fs.existsSync(sessionPath)) { fs.rmSync(sessionPath, {
recursive: true, // soll via config
force: true // soll via config
});
} console.clear();
return startWhatsAppBotMadeByHonneybuuModz();
} if (choice !== 'y') { return startWhatsAppBotMadeByHonneybuuModz();
} choice = 'y';
} else { console.log(`${noSession}\n`);
choice = await question(`${c.bgMagenta}${c.black}${c.bold} Deine Wahl: ${c.reset}`);
choice = choice.toLowerCase().trim();
if (choice === 'x') { process.exit(0);
} if (choice !== 'q' && choice !== 'p') { return startWhatsAppBotMadeByHonneybuuModz();
} } const { state, saveCreds } = await buuBotAuthState(sessionPath);
const { version } = await fetchLatestBaileysVersion();
const sock = makeWASocket({ version, auth: { creds: state.creds, keys: makeCacheableSignalKeyStore(state.keys, logger) }, logger, printQRInTerminal: false, browser: [ conf.browserInfo, conf.browserBla, conf.browserVersion ] });
currentSock = sock;
sock.sendJson = async (jid, json = {}, cfg = {}) => { try { const message = generateWAMessageFromContent(jid, proto.Message.fromObject(json), cfg);
return await sock.relayMessage(jid, message.message, { messageId: message.key.id });
} catch (err) { console.error(err);
} };
if (choice === 'p' && !state.creds.registered) { console.clear();
console.log(`\n${c.bgCyan}${c.black}${c.bold}${cs2}${c.reset}\n${c.bgMagenta}${c.black}${c.bold} Bitte gib deine Telefonnummer mit Ländervorwahl ein. ${c.reset}\n${c.cyan}Beispiel: ${c.bold}${c.green}4917612345678${c.reset}\n${c.bgCyan}${c.black}${c.bold}${cs2}${c.reset}`);
let phone = await question(`${c.bgMagenta}${c.black}${c.bold} Nummer: ${c.reset}`);
phone = phone.replace(/[^0-9]/g, '');
if (phone.length > 5) { 
console.clear();
console.log(`\n${c.yellow}⏳ Warte auf Pairing-Code von WhatsApp...${c.reset}`);
setupAbortListener();
setTimeout(async () => { try { const code = await sock.requestPairingCode(phone);
if (code) { console.clear();
const buuClientColoredPairingCode = formatSmartPairingCodeColor(code);
console.log(`${getPairingCodeOutput(buuClientColoredPairingCode)}\n`);
} } catch (err) { disableAbortListener();
} }, 2743);
} else { return startWhatsAppBotMadeByHonneybuuModz();
} }
sock.ev.on('creds.update', saveCreds);
sock.ev.on('connection.update', async (update) => { const { connection, lastDisconnect, qr } = update;

if (qr && choice === 'q') { console.clear();
qrcode.generate(qr, { small: conf.useQrCodeSmall });
console.log(`${c.bgCyan}${c.black}${c.bold}${cs2}${c.reset}\n${c.bold}${c.bgWhite}${c.black}Scanne den QR-Code mit deinem Handy.\n(alternativ WhatsApp Web)${c.reset}\n\n${c.magenta}[b]${c.reset}${c.bgMagenta}${c.black}Back to Menu${c.reset}\n\n${c.cyan}[x]${c.reset}${c.bgCyan}${c.black}Exit Script${c.reset}\n${c.bgCyan}${c.black}${c.bold}${cs2}${c.reset}\n`);
setupAbortListener();
} if (connection === 'open') { disableAbortListener();
console.clear();
console.log(`\n${c.bgGreen}${c.black}${c.bold} ✓ STATUS: ONLINE ${c.reset}`);
console.log(`${c.yellow}📦 Analysiere alten Hauptordner /buuUsers/ auf unstrukturierte Profile...${c.reset}`);
await migrateOldBuuUsers();
console.log(`${c.blue}🔄 Starte BUU-ID-MAPPING Synchronisation...${c.reset}`);
await syncAllBuuUsers();
if (!mappingInterval) { mappingInterval = setInterval(async () => { await syncAllBuuUsers(); }, 1000 * 60);
} } if (connection === 'close') { disableAbortListener();
const reason = lastDisconnect?.error?.output?.statusCode;
const shouldReconnect = reason !== DisconnectReason.loggedOut;
if (shouldReconnect) { console.log(`\n${c.yellow}⏳ Verbindung geschlossen.\nStarte in ca 5 Sekunden neu...${c.reset}`);
setTimeout(() => startWhatsAppBotMadeByHonneybuuModz(), 4743);
} } });
sock.ev.on('messages.upsert', async (m) => { await handler(sock, m, store);
});
} export async function sendJson(jid, json = {}, cfg = {}) { if (!currentSock) { console.error("sendJson aufgerufen, aber sock ist noch nicht bereit!");
return;
} try { const message = generateWAMessageFromContent(jid, proto.Message.fromObject(json), cfg);
return await currentSock.relayMessage(jid, message.message, { messageId: message.key.id });
} catch (err) { console.error(err);
} } startWhatsAppBotMadeByHonneybuuModz();