// importer.js
import fs from 'fs';
import fs2 from 'fs/promises';
import qrcode from 'qrcode-terminal';
import pino from 'pino';
import { createRequire } from 'module';
const requireWSB = createRequire(import.meta.url);
const whiskeysocketsBaileys = requireWSB('@whiskeysockets/baileys');
const { default: makeWASocket, sock, useMultiFileAuthState, fetchLatestBaileysVersion, makeCacheableSignalKeyStore, store, DisconnectReason, generateWAMessageFromContent, prepareWAMessageMedia, generateMessageID, proto, ACCOUNT_RESTRICTED_TEXT, ALL_WA_PATCH_NAMES, BinaryInfo, Browsers, BufferJSON, CALL_AUDIO_PREFIX, CALL_VIDEO_PREFIX, CompanionWebClientType, Curve, DECRYPTION_RETRY_CONFIG, DEFAULT_CACHE_TTLS, DEFAULT_CONNECTION_CONFIG, DEFAULT_ORIGIN, DEF_CALLBACK_PREFIX, DEF_MEDIA_HOST, DEF_TAG_PREFIX, DICT_VERSION, FLAG_BYTE, FLAG_EVENT, FLAG_EXTENDED, FLAG_FIELD, FLAG_GLOBAL, HISTORY_SYNC_PAUSED_TIMEOUT_MS, INITIAL_PREKEY_COUNT, KEY_BUNDLE_TYPE, LT_HASH_ANTI_TAMPERING, MAX_SYNC_ATTEMPTS, MEDIA_HKDF_KEY_MAPPING, MEDIA_KEYS, MEDIA_PATH_MAP, META_AI_JID, MIN_PREKEY_COUNT, MISSING_KEYS_ERROR_TEXT, MessageRetryManager, NACK_REASONS, NOISE_MODE, NOISE_WA_HEADER, NO_MESSAGE_FOUND_ERROR_TEXT, NewChatMessageCappingMVStatusType, NewChatMessageCappingOTEStatusType, NewChatMessageCappingStatusType, OFFICIAL_BIZ_JID, PHONE_CONNECTION_CB, PLACEHOLDER_MAX_AGE_SECONDS, PROCESSABLE_HISTORY_TYPES, PSA_WID, QueryIds, ReachoutTimelockEnforcementType, RetryReason, SERVER_ERROR_CODES, SERVER_JID, STATUS_EXPIRY_SECONDS, STORIES_JID, S_WHATSAPP_NET, SyncState, TimeMs, UNAUTHORIZED_CODES, UPLOAD_TIMEOUT, URL_REGEX, USyncContactProtocol, USyncDeviceProtocol, USyncDisappearingModeProtocol, USyncQuery, USyncStatusProtocol, USyncUser, USyncUsernameProtocol } = whiskeysocketsBaileys;
const buuBotAuthState = useMultiFileAuthState || (whiskeysocketsBaileys.default && whiskeysocketsBaileys.default.useMultiFileAuthState);
import { Buffer } from 'node:buffer';
import { createReadStream, createWriteStream } from 'node:fs';
import { writeFile, readFile, readdir, mkdir, rm, stat, access, watch, glob, lstat, cp, rename, link } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { pipeline, finished } from 'node:stream/promises';
import { Readable, Writable, Transform, Duplex, addAbortSignal } from 'node:stream';
import { promisify, styleText, parseArgs, inspect, format } from 'node:util';
import { performance, PerformanceObserver } from 'node:perf_hooks';
import * as readline from 'node:readline/promises';
import { stdin as input, stdout as output, stderr, env, exit, argv, cwd, pid } from 'node:process';
import { spawn, exec, execSync, fork, execFile } from 'node:child_process';
import { Worker, isMainThread, parentPort, MessageChannel, MessagePort } from 'node:worker_threads';
import { randomUUID, randomBytes, createHash, createHmac, scrypt, scryptSync, createCipheriv, createDecipheriv } from 'node:crypto';
import { createServer } from 'node:http';
import { createServer as createHttpsServer } from 'node:https';
import http2 from 'node:http2';
import { DatabaseSync } from 'node:sqlite';
import { gzip, gunzip, deflate, inflate } from 'node:zlib';
import { test, describe, it, before, beforeEach, after, afterEach, mock } from 'node:test';
import assert from 'node:assert';
const createServer2 = http2.createSecureServer;
const createHttp2SecureServer = http2.createSecureServer;
const fetchApi = globalThis.fetch;
const execAsync = promisify(exec);
const execFileAsync = promisify(execFile);
const gzipAsync = promisify(gzip);
const gunzipAsync = promisify(gunzip);
const idk = "Unbekannt";
let pkg = {};
try { pkg = JSON.parse(fs.readFileSync('./package.json', 'utf-8'));
} catch (e) { pkg = { version: idk };
} const cs = "ⲶⲼ".repeat(13);
// 
export { pkg, fs, fs2, qrcode, pino, cs, idk, Buffer, createReadStream, createWriteStream, writeFile, readFile, readdir, mkdir, rm, stat, access, watch, glob, lstat, cp, rename, link, path, fileURLToPath, pathToFileURL, pipeline, finished, addAbortSignal, Readable, Writable, Transform, Duplex, promisify, styleText, parseArgs, inspect, format, performance, PerformanceObserver, readline, input, output, stderr, env, exit, argv, cwd, pid, spawn, exec, execSync, fork, execFile, execAsync, execFileAsync, Worker, isMainThread, parentPort, MessageChannel, MessagePort, randomUUID, randomBytes, createHash, createHmac, scrypt, scryptSync, createCipheriv, createDecipheriv, createServer, createHttpsServer, http2, createServer2, createHttp2SecureServer, fetchApi, DatabaseSync, gzip, gunzip, deflate, inflate, gzipAsync, gunzipAsync, test, describe, it, before, beforeEach, after, afterEach, mock, assert, whiskeysocketsBaileys, createRequire, makeWASocket, buuBotAuthState, fetchLatestBaileysVersion, makeCacheableSignalKeyStore, store, DisconnectReason, generateWAMessageFromContent, prepareWAMessageMedia, generateMessageID, proto };
//export { pkg, fs, fs2, qrcode, pino, cs, idk, Buffer, createReadStream, createWriteStream, writeFile, readFile, readdir, mkdir, rm, stat, access, watch, glob, lstat, cp, rename, link, path, fileURLToPath, pathToFileURL, pipeline, finished, addAbortSignal, Readable, Writable, Transform, Duplex, promisify, styleText, parseArgs, inspect, format, performance, PerformanceObserver, readline, input, output, stderr, env, exit, argv, cwd, pid, spawn, exec, execSync, fork, execFile, execAsync, execFileAsync, Worker, isMainThread, parentPort, MessageChannel, MessagePort, randomUUID, randomBytes, createHash, createHmac, scrypt, scryptSync, createCipheriv, createDecipheriv, createServer, createHttpsServer, http2, createServer2, createHttp2SecureServer, fetchApi, DatabaseSync, gzip, gunzip, deflate, inflate, gzipAsync, gunzipAsync, test, describe, it, before, beforeEach, after, afterEach, mock, assert, whiskeysocketsBaileys, createRequire, sock, makeWASocket, buuBotAuthState, fetchLatestBaileysVersion, makeCacheableSignalKeyStore, store, DisconnectReason, generateWAMessageFromContent, prepareWAMessageMedia, generateMessageID, proto };
